"""preferences table

Revision ID: 21b15d44e5fd
Revises: 922d2aa8dcf0
Create Date: 2018-11-26 16:00:28.542290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21b15d44e5fd'
down_revision = '922d2aa8dcf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genre', sa.String(length=140), nullable=True),
    sa.Column('actor', sa.String(length=140), nullable=True),
    sa.Column('rating', sa.String(length=140), nullable=True),
    sa.Column('director', sa.String(length=140), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('preference')
    # ### end Alembic commands ###
